# Generated by Django 2.2.7 on 2019-11-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='check_out_time',
            new_name='check_out_time_temp',
        ),
    ]
